using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Globalization;
using Microsoft.Pex.Framework.Generated;
// <copyright file="NumberFormatConverterTest.Convert.g.cs">Copyright ©  2015, Mike Ward</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;
using MarkdownEdit.Converters;

namespace MarkdownEdit
{
    public partial class NumberFormatConverterTest
    {
[TestMethod]
[PexGeneratedBy(typeof(NumberFormatConverterTest))]
public void Convert776()
{
    object o;
    NumberFormatConverter s0 = new NumberFormatConverter();
    object boxi = (object)(default(int));
    PexSafeHelpers.AssignBoxedValue<int>(boxi, int.MaxValue);
    o = this.Convert(s0, boxi, (Type)null, (object)null, (CultureInfo)null);
    Assert.IsNotNull(o);
    Assert.IsNotNull((object)s0);
}
[TestMethod]
[PexGeneratedBy(typeof(NumberFormatConverterTest))]
public void Convert287()
{
    object o;
    NumberFormatConverter s0 = new NumberFormatConverter();
    o = this.Convert(s0, (object)null, (Type)null, (object)null, (CultureInfo)null);
    Assert.IsNull(o);
    Assert.IsNotNull((object)s0);
}
[TestMethod]
[PexGeneratedBy(typeof(NumberFormatConverterTest))]
public void Convert804()
{
    object o;
    NumberFormatConverter s0 = new NumberFormatConverter();
    object boxi = (object)(default(int));
    o = this.Convert(s0, boxi, (Type)null, (object)null, (CultureInfo)null);
    Assert.IsNotNull(o);
    Assert.IsNotNull((object)s0);
}
[TestMethod]
[PexGeneratedBy(typeof(NumberFormatConverterTest))]
public void Convert740()
{
    object o;
    NumberFormatConverter s0 = new NumberFormatConverter();
    object boxi = (object)(default(int));
    PexSafeHelpers.AssignBoxedValue<int>(boxi, 1);
    o = this.Convert(s0, boxi, (Type)null, (object)null, (CultureInfo)null);
    Assert.IsNotNull(o);
    Assert.IsNotNull((object)s0);
}
[TestMethod]
[PexGeneratedBy(typeof(NumberFormatConverterTest))]
public void Convert328()
{
    object o;
    NumberFormatConverter s0 = new NumberFormatConverter();
    object boxi = (object)(default(int));
    PexSafeHelpers.AssignBoxedValue<int>(boxi, int.MinValue);
    o = this.Convert(s0, boxi, (Type)null, (object)null, (CultureInfo)null);
    Assert.IsNotNull(o);
    Assert.IsNotNull((object)s0);
}
    }
}
