using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="UtilityTest.Memoize.g.cs">Copyright ©  2015, Mike Ward</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace MarkdownEdit.Models
{
    public partial class UtilityTest
    {
[TestMethod]
[PexGeneratedBy(typeof(UtilityTest))]
public void Memoize727()
{
    Func<int, int> func;
    func = this.Memoize<int, int>((Func<int, int>)null);
    Assert.IsNotNull((object)func);
}
    }
}
