using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.IO;
using Microsoft.Pex.Framework.Generated;
// <copyright file="UtilityTest.WatchFile.g.cs">Copyright ©  2015, Mike Ward</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace MarkdownEdit.Models
{
    public partial class UtilityTest
    {
[TestMethod]
[PexGeneratedBy(typeof(UtilityTest))]
[PexRaisedException(typeof(ArgumentException))]
public void WatchFileThrowsArgumentException574()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      FileSystemWatcher fileSystemWatcher;
      fileSystemWatcher = this.WatchFile((string)null, (Action)null);
      disposables.Add((IDisposable)fileSystemWatcher);
      disposables.Dispose();
    }
}
    }
}
