//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkdownEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkdownEdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;Markdown Edit Preview&lt;/title&gt;
        ///  &lt;!-- Don&apos;t delete this X-UA tag. The browser control behaves like IE8 otherwise --&gt;
        ///  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot;&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=utf-8&quot; /&gt;
        ///  &lt;style type=&quot;text/css&quot;&gt;
        ///    body {
        ///      font-family: &quot;Century Gothic&quot;, Arial;
        ///      font-size: 15px;
        ///      line-height: 1.5;
        ///      color: #555;
        ///      padding: 0.5pc 0;
        ///      overflow-x: hidden;
        ///      overflow-y: scroll;
        ///      backg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GithubTemplateHtml {
            get {
                return ResourceManager.GetString("GithubTemplateHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Keyboard Shortcuts
        ///
        ///    F1             Show/Hide this help
        ///
        ///    Ctrl+N         New file
        ///    Ctrl+O         Open file
        ///    Ctrl+S         Save file
        ///    Ctrl+Shift+S   Save file As
        ///    Ctrl+R         Recent files
        ///    Ctrl+E         Export HTML to clipboard
        ///    Alt+F4         Exit
        ///
        ///    Ctrl+W         Toggle word wrap
        ///    F7             Toggle spell checking
        ///    F11            Toggle full screen
        ///    F12            Toggle preview
        ///    
        ///    Tab            Indent current line/selection 2 spaces
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name=&quot;MarkDown&quot; extensions=&quot;.md&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///	&lt;Color name=&quot;Heading&quot;         fontWeight=&quot;bold&quot; /&gt;
        ///	&lt;Color name=&quot;Emphasis&quot;        fontStyle=&quot;italic&quot; /&gt;
        ///	&lt;Color name=&quot;StrongEmphasis&quot;  fontWeight=&quot;bold&quot; /&gt;
        ///	&lt;Color name=&quot;InlineCode&quot;      foreground=&quot;#654&quot; background=&quot;#e9e6e3&quot; /&gt;
        ///	&lt;Color name=&quot;BlockCode&quot;       foreground=&quot;#654&quot; /&gt;
        ///	&lt;Color name=&quot;BlockQuote&quot;      foreground=&quot;#654&quot; /&gt;
        ///	&lt;Color name=&quot;Link&quot;            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string markdown_xshd {
            get {
                return ResourceManager.GetString("markdown_xshd", resourceCulture);
            }
        }
    }
}
